---
- hosts: webservers
  gather_facts: yes
  become_user: root
  tasks:
  - name: Install apache2
    apt: pkg=apache2 state=present
    notify:
    - restart apache2
  - name: Enable apache2 during boot
    service: name=apache2 state=started enabled=yes
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted